local helper = require("assets.level.helper")

helper.addGrassClump("nest.ground",   11,    0.5, nil, 5.25) -- Plant pot grass
helper.addGrassClump("nest.ground", 25.5,    0.5, 3.5, 3) -- Plant pot large grass
helper.addGrassClump("nest.ground", 25.5,    1.5, 3.5, 3) -- Plant pot large grass
helper.addGrassClump("nest.ground",   -7,   -6)
helper.addGrassClump("nest.ground",   -3,  -17)
helper.addGrassClump("nest.ground",    8,   -6)
helper.addGrassClump("nest.ground",   14,  -19)
helper.addGrassClump("nest.ground",   -9,    5)
helper.addGrassClump("nest.ground",    8,    7)
helper.addGrassClump("nest.ground",    7,  -15)
helper.addGrassClump("nest.ground",   22,  -13)
helper.addPebbleClump("nest.ground",   4,  -18)
helper.addPebbleClump("nest.ground",  20,  -24)
helper.addPebbleClump("nest.ground", -16,  -16)
helper.addPebbleClump("nest.ground", -14,   -3.5)
helper.addPebbleClump("nest.ground",  13,    6)
helper.addPebbleClump("nest.ground", -13,  -25.5)
helper.addPebbleClump("nest.ground",   9,  -18)
helper.addPebbleClump("nest.ground",  22,  -13)
helper.addGrassClump("nest.ground",  -12,  -16.5)
helper.addGrassClump("nest.ground",  -25,  -10)
helper.addPebbleClump("nest.ground", -24,  -19)
helper.addGrassClump("nest.ground",  -24,  -19)
helper.addPebbleClump("nest.ground", -10, -8)
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(-2, -13, -15, -13, -23, -2))
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(2, -13, 19, -12.5, 29.5, -7))
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(0, -13.5, 0, -8))
helper.addPebbleClump("nest.ground", -25, -26)
helper.addPebbleClump("nest.ground", -9, -30)
helper.addGrassClump("nest.ground", -9, -29)
helper.addGrassClump("nest.ground", 19.5, -28)
helper.addPlant("nest.ground", 2.5, -17.5)
helper.addPlant("nest.ground", -8, -16)
helper.addPlant("nest.ground", -8, -3)
helper.addPlant("nest.ground", -20, -12)
helper.addPlant("nest.ground", 18, -17)
helper.addPlant("nest.ground", 24, -15.5)
helper.addPlant("nest.ground", 5, -7.5)
helper.addPlant("nest.ground", 10.5, -4.5)
helper.addPlant("nest.ground", 29, -11)
helper.addPlant("nest.ground", 23.25, 11.25)
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(20, -4.5, 16, 0, 20, 9))
helper.addGrassClump("nest.ground", 22.5, 6.5)
helper.addGrassClump("nest.ground", 17.5, 14)
helper.addGrassClump("nest.ground", 23.5, -6)
helper.addGrassClump("nest.ground", 12, -8)
helper.addGrassClump("nest.ground", 15.5, 0)
helper.addPlant("nest.ground", 15, 7)
helper.addPlant("nest.ground", 20.6, 2.5)
helper.addPlant("nest.pot", 22.9, 2.1, -1)
helper.addSmallRock("nest.ground", -5.5, -9)
helper.addSmallRock("nest.ground", -8, -17.5)
helper.addSmallRock("nest.ground", 17.5, -7)
helper.addSmallRock("nest.ground", 26.5, -5)
helper.addSmallRock("nest.ground", 0, 8)
helper.addGrassClump("nest.ground", 12.5, 15)
helper.addPebbleClump("nest.ground", -6.5, 10)
helper.addLargeRock({ "nest.ground", "zone1.ground" }, -32, -12.5)
helper.addLargeRock({ "nest.ground", "tutorial.ground" }, 25, -24)
helper.addLargeRock({ "nest.ground", "tutorial.ground" }, 35.5, -16.5)
helper.addSmallRock("nest.ground", 28, -18)
helper.addGrassClump("nest.ground", 24, -23, 1)
helper.addGrassClump("nest.ground", 32, -25, 0.5)
helper.addPebbleClump("nest.ground", 31, -20)
helper.addLargeRock("nest.ground", 5.5, 21)
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(-4.5, 15.5, -1.5, 16.5, -2.5, 21.5))
helper.addGrassClump("nest.ground", 4, 15)
helper.addGrassClump("nest.ground", -0.5, 19.5)
helper.addPlant("nest.ground", 2.5, 15)
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(-16, 5.5, -9, 11.5, -2.5, 11.5))
helper.addPlant("nest.ground", -6.5, 6)
helper.addSmallRock("nest.ground", -14, 3)
helper.addCabbage({ "nest.ground", "tutorial.ground" }, -28, -17)
helper.addPlant("nest.ground", -26.5, -5)
helper.addLargeRock("nest.ground", 23, 22)
helper.addCabbage("nest.ground", 15, 25)
helper.addGrassClump("nest.ground", 24, 29.5)
helper.addCabbage("nest.ground", 33.5, 8)
helper.addSmallRock("nest.ground", 30, 6)
helper.addGrassClump("nest.ground", 29, 10.5)
helper.addPlant("nest.ground", 20.5, 17.5)
helper.addPebbleClump("nest.ground", 12, 20)
helper.addSmallRock("nest.ground", 11, 19)
helper.addGrassClump("nest.ground", 33.5, 2)
helper.addSmallRock("nest.ground", 0.5, 27)
helper.addGrassClump("nest.ground", -7, 25)
helper.addGrassClump("nest.ground", -1, 27)
helper.addPlant("nest.ground", -5.2, 23)
helper.addGrassClump("nest.ground", -10, 14)
helper.addLargeRock("nest.ground", -21, 15)
helper.addCabbage("nest.ground", -17, 20.5)
helper.addCabbage("nest.ground", -21, 33.5)
helper.addSmallRock("nest.ground", -15, 16)
helper.addGrassClump("nest.ground", -13.5, 25.5)
helper.addLargeRock("nest.ground", -27, 26)
helper.addCabbage("nest.ground", -25.5, 20)
helper.addGrassClump("nest.ground", -21.5, 19)
helper.addGrassClump("nest.ground", -19, 28)
helper.addPlant("nest.ground", -21, 19)
helper.addCabbage("nest.ground", -10.5, 30)
helper.addPlant("nest.ground", -16.5, 30.5)
helper.addGrassClump("nest.ground", -12, 19)
helper.addPlant("nest.ground", 0.5, 30)
helper.addGrassClump("nest.ground", 7, 28)
helper.addCabbage("nest.ground", 10, 33)
helper.addLargeRock("nest.ground", 21, 36)
helper.addGrassClump("nest.ground", 5, 39)
helper.addGrassClump("nest.ground", 0, 44)
helper.addSmallRock("nest.ground", 14.5, 37)
helper.addPebbleClump("nest.ground", 8.5, 37.5)
helper.addPlant("nest.ground", 7.5, 40.5)
helper.addLargeRock("nest.ground", 15, 38.5)
helper.addPlant("nest.ground", 17.5, 33.5)
helper.addPlant("nest.ground", 15.5, 31)
helper.addGrassClump("nest.ground", 15, 31.5)
helper.addCabbage("nest.ground", 31.5, 20.5)
helper.addGrassClump("nest.ground", 18, 23)
helper.addLargeRock("nest.ground", 37.5, 14.5)
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(23, 16, 28, 8.5))
helper.addGrassClump("nest.ground", 29, 16)
helper.addPebbleClump("nest.ground", 27.5, 16)
helper.addPlant("nest.ground", 33, 13)
helper.placeDirtPath("nest.ground", love.math.newBezierCurve(-23, -1.5, -24.5, 6, -32, 3.5))
helper.addCabbage("nest.ground", -21, 6)
helper.addGrassClump("nest.ground", -17, 10.5)
helper.addGrassClump("nest.ground", -23, 9)
helper.addGrassClump("nest.ground", -19, -.5)
helper.addCabbage({ "nest.ground", "zone1.ground" }, -31, -2)
helper.addPlant({ "nest.ground", "zone1.ground" }, -29, 9)
helper.addGrassClump("nest.ground", -28, -1)
helper.addPlant({ "nest.ground", "zone1.ground" }, -32.5, -5.5)
helper.addPebbleClump("nest.ground", -28.5, -5.5)
helper.addGrassClump("nest.ground", -26, 11)
helper.addCabbage("nest.ground", -25, 28)
helper.addSmashablePot("nest.ground", -8, -8)
helper.addSmashablePot("nest.ground", 9, -8)
helper.addSmashablePot("nest.ground", 8.5, -7)
helper.addSmashablePot("nest.ground", 9.5, -7)
helper.addSmashablePot("nest.ground", 22, -18)
helper.addSmashablePot("nest.ground", 25.5, 13)

helper.addSmashablePot("nest.ground", 0, 12.5)
helper.addSmashablePot("nest.ground", -1, 11.5)
helper.addSmashablePot("nest.ground", 1, 11.5)
helper.addSmashablePot("nest.ground", 0, 10.5)

helper.addSmashablePot("nest.ground", -18, 2.5)
helper.addSmashablePot("nest.ground", -17.5, 4)
helper.addSmashablePot("nest.ground", -16, 3)

helper.addSmashablePot("nest.ground", -17, 26.5)
helper.addSmashablePot("nest.ground", 21, 25.5)

helper.addSmashablePot("nest.ground", 22, 9.5)
helper.addSmashablePot("nest.ground", 20.5, 10)
helper.addSmashablePot("nest.ground", 19, 10.5)