local helper = require("assets.level.helper")

helper.addPlant({ "nest.ground", "tutorial.ground" }, 18, -23)
helper.addSmallRock({ "nest.ground", "tutorial.ground" }, 16.5, -23)
helper.addLargeRock({ "nest.ground", "tutorial.ground" }, -12.0, -22)
helper.placeDirtPath("tutorial.ground", love.math.newBezierCurve({ 0, -19, 6, -26, -8, -30, 2, -36}))

helper.addCliff({ "tutorial.ground", "tutorial.upper" }, 14, -32, 0, math.rad(-90))
helper.addCliff({ "tutorial.ground", "tutorial.upper" }, 29.5, -32, 0, math.rad(90))

helper.addTallRock("tutorial.ground", 13, -28.5)
helper.addTallRock("tutorial.ground", 18, -27.5)
helper.addTallRock("tutorial.ground", 22, -28)
helper.addTallRock("tutorial.ground", 24, -30)
helper.addTallRock("tutorial.ground", 26, -29)
helper.addTallRock("tutorial.ground", 28.5, -28)
helper.addTallRock("tutorial.ground", 31, -28.5)

helper.addTallRock("tutorial.ground", -7, -42)
helper.addTallRock("tutorial.ground", -22, -21.5)
helper.addTallRock({ "nest.ground", "tutorial.ground" }, 32, -21)
helper.addTallRock({ "nest.ground", "tutorial.ground" }, 38, -13.5)
helper.addCollectable("LEAF", "tutorial.ground", 1.5, -24.5, "tutorial")
helper.addTallRock("tutorial.ground", 8.5, -27)
helper.addPlant("tutorial.ground", 9.5, -31)

helper.addCliff("tutorial.ground", 14, -37, 0, math.rad(-90), true)
helper.addCliff("tutorial.ground", 29.5, -37, 0, math.rad(90), true)

local length = 5
for y = 0, length * 5, 5 do
  helper.addCliff({ "tutorial.ground", "tutorial.upper" }, 14, -42 - y, 0, math.rad(-90))
  helper.addCliff({ "tutorial.ground", "tutorial.upper" }, 29.5, -42 - y, 0, math.rad(90))
end

helper.addCollectable("LEAF", "tutorial.ground", -1.5, -31, "tutorial")

helper.addTallRock("tutorial.ground", 12.4, -46)
helper.addLargeRock("tutorial.ground", 2, -50)
helper.addCabbage("tutorial.ground", 3, -49)
helper.addGrassClump("tutorial.ground", 5, -41)
helper.addPebbleClump("tutorial.ground", 10, -33)
helper.addPebbleClump("tutorial.ground", 9, -43)
helper.addTallRock("tutorial.ground", 9.5, -50.5)
helper.addGrassClump("tutorial.ground", 5.2, -49, nil, 0.2)
helper.addSmallRock("tutorial.ground", 7.5, -45.5)
helper.addPlant("tutorial.ground", 8.7, -46.8)
helper.addPlant("tutorial.ground", 3.5, -34.5)
helper.addCollectable("LEAF", "tutorial.ground", 1.5, -35.5, "tutorial")
helper.addSmallRock("tutorial.ground", 4.5, -39)
helper.addPlant("tutorial.ground", 11, -39.5)
helper.addGrassClump("tutorial.ground", 10, 38)
helper.addGrassClump("tutorial.ground", -6, -49)
helper.addPlant("tutorial.ground", -11, -47)
helper.addCabbage("tutorial.ground", -12.5, -36)
helper.addLargeRock("tutorial.ground", -15, -31)
helper.addCabbage("tutorial.ground", -15, -44.5)
helper.addGrassClump("tutorial.ground", -19, -35)
helper.addGrassClump("tutorial.ground", -3, -37)
helper.addTallRock({ "tutorial.ground", "tutorial.upper" }, 16, -30.5, 2.5)
helper.addPlant("tutorial.upper", 14, -39.5)
helper.addTallRock({ "tutorial.upper", "tutorial.ground" }, 20.5, -31)
-- helper.addTallRock({ "tutorial.ground", "tutorial.upper" }, 29, -33, 3.5)
helper.addPlant("tutorial.upper", 18.5, -34.5)
helper.addPlant("tutorial.upper", 25, -33)
helper.addPlant("tutorial.ground", 11.5, -33)
helper.addCabbage("tutorial.upper", 18.5, -46.5)
helper.addCabbage("tutorial.upper", 26, -44.5)
helper.addSmallRock("tutorial.upper", 23, -45)
helper.addGrassClump("tutorial.upper", 20, -40)
helper.addGrassClump("tutorial.upper", 25.5, -35)
helper.addPlant("tutorial.ground", -8.5, -38)
helper.addGrassClump("tutorial.ground", 3.5, -29)
helper.addPebbleClump("tutorial.upper", 17, -33.5)
helper.addPebbleClump("tutorial.upper", 27, -31.5)
helper.addPlant("tutorial.upper", 28.5, -40.5)
helper.addGrassClump("tutorial.ground", 32, -39.5)
helper.addPebbleClump("tutorial.ground", 37, -26)
helper.addPebbleClump("tutorial.ground", 34.5, -32)
helper.addPlant("tutorial.ground", 39.5, -39)
helper.addCollectable("LEAF", "tutorial.upper", 28.5, -36.5, "tutorial")
helper.addCabbage("tutorial.ground", 33.5, -46)
helper.addSmallRock("tutorial.ground", 29.5, -36.5, nil, nil, "tutorial.rock.logBlock")
helper.addPlant("tutorial.ground", 40, -34.5)

helper.placeDirtPath("tutorial.ground", love.math.newBezierCurve(48, -52, 55, -42.5, 48, -36.5))
helper.addCollectable("LEAF", "tutorial.ground", 52, -44, "tutorial")
helper.addCabbage("tutorial.ground", 44, -43)
helper.addCabbage("tutorial.ground", 44.5, -26)
helper.addCabbage("tutorial.ground", 61, -37)
helper.addLargeRock("tutorial.ground", 65, -51)
helper.addCabbage("tutorial.ground", 59.5, -56.5)
helper.addCabbage("tutorial.ground", 32, -54.5)
helper.addCabbage("tutorial.ground", 50, -61.5)
helper.addTallRock("tutorial.ground", 41, -21)
helper.addLargeRock("tutorial.ground", 57, -27)
helper.addLargeRock("tutorial.ground", 50, -21.5)
helper.addCabbage("tutorial.ground", 55, -26)
helper.addPlant("tutorial.ground", 56.5, -33)
helper.addSmallRock("tutorial.ground", 60, -34)
helper.addGrassClump("tutorial.ground", 51, -31.5)
helper.addGrassClump("tutorial.ground", 57, -42)
helper.addPebbleClump("tutorial.ground", 55, -37)
helper.addGrassClump("tutorial.ground", 43, -32)
helper.addGrassClump("tutorial.ground", 33, -34)
helper.addCollectable("LEAF", "tutorial.ground", 49, -36.5, "tutorial")
helper.addGrassClump("tutorial.ground", 36, -50.1)
helper.addLargeRock("tutorial.ground", 39.5, -61.5)
helper.addCabbage("tutorial.ground", 36.5, -60)
helper.addGrassClump("tutorial.ground", 43.5, -57.5)
helper.addGrassClump("tutorial.ground", 43.5, -47.5)
helper.addPlant("tutorial.ground", 37, -57)
helper.addLargeRock("tutorial.ground", 58, -61.5)
helper.addSmallRock("tutorial.ground", 47, -61)
helper.addGrassClump("tutorial.ground", 48, -67)
helper.addGrassClump("tutorial.ground", 58, -68)
helper.addGrassClump("tutorial.ground", 68, -56)
helper.addCabbage("tutorial.ground", 57, -48)
helper.addSmallRock("tutorial.ground", 31, -50)
helper.addCabbage("tutorial.ground", 66.5, -65.5)
helper.addCabbage("tutorial.ground", 42, -68)
helper.addCabbage("tutorial.ground", 55, -73)
helper.addCabbage("tutorial.ground", 72, -55)
helper.addCabbage("tutorial.ground", 63, -44)
helper.addCabbage("tutorial.ground", 56, -31)
helper.addCabbage("tutorial.ground", 63, -23)
helper.addLargeRock("tutorial.ground", 66, -40.5)
helper.addPebbleClump("tutorial.ground", 53, -56)
helper.addGrassClump("tutorial.ground", 73.5, -45)
helper.addCabbage("tutorial.ground", 72, -39)
helper.addCabbage("tutorial.ground", 69, -32)
helper.addGrassClump("tutorial.ground", 66.5, -28)
helper.addCabbage("tutorial.upper", 27, -53)
helper.addGrassClump("tutorial.upper", 27, -49)
helper.addGrassClump("tutorial.upper", 27, -59)
helper.addCabbage("tutorial.ground", -4, -47.5)
helper.addSmallRock("tutorial.ground", -14.5, -40)
helper.addSmallRock("tutorial.ground", -12.5, -46.5)
helper.addPlant("tutorial.ground", -8.5, 46.5)
helper.placeDirtPath("tutorial.upper", love.math.newBezierCurve(27.5, -37, 22, -35.5, 15.5, -36.5), 0.1)
helper.addSmallRock("tutorial.upper", 27, -30.5)
helper.addSmashablePot("tutorial.upper", 21.5, -36.5)
helper.addSmashablePot("tutorial.upper", 20.5, -36)
helper.addSmashablePot("tutorial.upper", 20.5, -37)
helper.addSmashablePot("tutorial.upper", 17, -41)
helper.addSmashablePot("tutorial.ground", -6, -33)
helper.addSmashablePot("tutorial.ground", 38, -26.5)
helper.addSmashablePot("tutorial.ground", 37.5, -25.5)
helper.addSmashablePot("tutorial.ground", 38.5, -25.5)
helper.addSmashablePot("tutorial.ground", 56, -37.5)